"""
Generated by scripts/codegen-schemas.ts from shared/schemas/*.schema.json
DO NOT EDIT MANUALLY — run `npm run codegen:schemas` to regenerate.
Protocol version: 1.0
"""

from __future__ import annotations

from typing import Any, Literal, TypedDict, Union

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROTOCOL_VERSION: str = "1.0"

TASK_FAILURE_REASONS = (
    "step_budget_exhausted",
    "token_budget_exhausted",
    "sandbox_violation",
    "llm_error",
    "cdp_error",
    "internal_error",
)

GOOGLE_OAUTH_SCOPES = (
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/documents",
)

# ---------------------------------------------------------------------------
# Shared primitives
# ---------------------------------------------------------------------------


class ErrorDetail(TypedDict):
    code: str
    message: str
    retryable: bool


# ---------------------------------------------------------------------------
# Requests (received by daemon from Electron main)
# ---------------------------------------------------------------------------


class AgentTaskRequest(TypedDict):
    version: Literal["1.0"]
    meta: Literal["agent_task"]
    prompt: str
    """User-supplied prompt."""
    per_target_cdp_url: str
    """Per-target CDP WebSocket URL: ws://host:port/devtools/page/{targetId}.
    Enforces active-tab-only at transport layer (plan principle #4)."""
    task_id: str
    """Unique task identifier (UUID recommended)."""


class CancelTaskRequest(TypedDict):
    version: Literal["1.0"]
    meta: Literal["cancel_task"]
    task_id: str


class SetActiveTargetRequest(TypedDict):
    version: Literal["1.0"]
    meta: Literal["set_active_target"]
    per_target_cdp_url: str


class PingRequest(TypedDict):
    version: Literal["1.0"]
    meta: Literal["ping"]


class ShutdownRequest(TypedDict):
    version: Literal["1.0"]
    meta: Literal["shutdown"]


DaemonRequest = Union[
    AgentTaskRequest,
    CancelTaskRequest,
    SetActiveTargetRequest,
    PingRequest,
    ShutdownRequest,
]

# ---------------------------------------------------------------------------
# Responses (sent by daemon to Electron main, synchronous reply)
# ---------------------------------------------------------------------------


class SuccessResponse(TypedDict):
    version: Literal["1.0"]
    ok: Literal[True]
    result: Any  # optional, may be absent


class ErrorResponse(TypedDict):
    version: Literal["1.0"]
    ok: Literal[False]
    error: ErrorDetail


DaemonResponse = Union[SuccessResponse, ErrorResponse]

# ---------------------------------------------------------------------------
# Push Events (sent by daemon to Electron main, unsolicited)
# ---------------------------------------------------------------------------


class TaskStartedEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["task_started"]
    task_id: str
    started_at: str  # ISO 8601


class StepStartEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["step_start"]
    task_id: str
    step: int  # 1-based
    plan: str


class StepResultEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["step_result"]
    task_id: str
    step: int
    result: Any
    duration_ms: int


class StepErrorEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["step_error"]
    task_id: str
    step: int
    error: ErrorDetail


class TaskDoneEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["task_done"]
    task_id: str
    result: Any
    steps_used: int
    tokens_used: int


class TaskFailedEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["task_failed"]
    task_id: str
    reason: str  # one of TASK_FAILURE_REASONS
    partial_result: Any  # optional, may be absent


class TaskCancelledEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["task_cancelled"]
    task_id: str


class TargetLostEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["target_lost"]
    task_id: str
    target_id: str  # CDP target ID that was detached


AgentEvent = Union[
    TaskStartedEvent,
    StepStartEvent,
    StepResultEvent,
    StepErrorEvent,
    TaskDoneEvent,
    TaskFailedEvent,
    TaskCancelledEvent,
    TargetLostEvent,
]

AGENT_EVENT_TYPES = (
    "task_started",
    "step_start",
    "step_result",
    "step_error",
    "task_done",
    "task_failed",
    "task_cancelled",
    "target_lost",
)

# ---------------------------------------------------------------------------
# Tab state (for reference; Tab state flows main ↔ renderer, not daemon)
# ---------------------------------------------------------------------------


class TabInfo(TypedDict, total=False):
    tab_id: str
    url: str
    title: str
    favicon_url: str  # optional
    is_loading: bool
    can_go_back: bool
    can_go_forward: bool
    per_target_cdp_url: str  # optional, set once tab navigated


# ---------------------------------------------------------------------------
# Onboarding messages (for reference; flows renderer ↔ main, not daemon)
# ---------------------------------------------------------------------------


class AccountInfo(TypedDict, total=False):
    email: str  # required
    display_name: str  # optional
    avatar_url: str  # optional


class OnboardingCompleteEvent(TypedDict):
    version: Literal["1.0"]
    event: Literal["onboarding-complete"]
    agent_name: str
    account: AccountInfo
    oauth_scopes: list[str]


# ---------------------------------------------------------------------------
# Runtime validation helpers
# ---------------------------------------------------------------------------


def assert_version(msg: Any) -> None:
    """Raise ValueError if msg lacks version field or has wrong version."""
    if not isinstance(msg, dict):
        raise ValueError(f"Expected dict, got {type(msg).__name__}")
    v = msg.get("version")
    if v is None:
        raise ValueError("IPC message missing 'version' field")
    if v != PROTOCOL_VERSION:
        raise ValueError(f"IPC version mismatch: expected {PROTOCOL_VERSION}, got {v!r}")


def make_success_response(result: Any = None) -> SuccessResponse:
    """Build a success response dict."""
    resp: SuccessResponse = {"version": PROTOCOL_VERSION, "ok": True, "result": result}
    return resp


def make_error_response(
    code: str,
    message: str,
    retryable: bool = False,
) -> ErrorResponse:
    """Build an error response dict. Never include raw stacktraces in message."""
    return {
        "version": PROTOCOL_VERSION,
        "ok": False,
        "error": {"code": code, "message": message, "retryable": retryable},
    }


def make_event(event_type: str, task_id: str, **kwargs: Any) -> dict:
    """Build an event dict with version stamped in."""
    return {"version": PROTOCOL_VERSION, "event": event_type, "task_id": task_id, **kwargs}


def parse_request(data: dict) -> DaemonRequest:
    """
    Validate and return a typed request dict.
    Raises ValueError with a safe message on any validation failure.
    """
    assert_version(data)
    meta = data.get("meta")
    if meta is None:
        raise ValueError("Request missing 'meta' field")
    if meta not in ("agent_task", "cancel_task", "set_active_target", "ping", "shutdown"):
        raise ValueError(f"Unknown request meta: {meta!r}")
    if meta == "agent_task":
        for field in ("prompt", "per_target_cdp_url", "task_id"):
            if not data.get(field):
                raise ValueError(f"agent_task request missing required field: {field!r}")
    if meta == "cancel_task" and not data.get("task_id"):
        raise ValueError("cancel_task request missing task_id")
    if meta == "set_active_target" and not data.get("per_target_cdp_url"):
        raise ValueError("set_active_target request missing per_target_cdp_url")
    return data  # type: ignore[return-value]
